extends Node

signal game_state_changed(old_state: int, new_state: int)
signal dialogue_started(dialogue_id: String)
signal dialogue_ended(dialogue_id: String)
signal dialogue_node_reached(node_id: String)
signal choice_made(choice_id: String, option_index: int)
signal evidence_discovered(evidence_id: String)
signal evidence_analyzed(evidence_id: String, analysis_type: String, result: String)
signal interrogation_started(suspect_id: String)
signal interrogation_ended(suspect_id: String, quality_score: float)
signal deduction_submitted(case_id: String, answers: Dictionary)
signal case_completed(case_id: String, score: int, points_earned: int)
signal system_points_changed(old_value: int, new_value: int)
signal attribute_changed(attribute_name: String, old_value: int, new_value: int)
signal item_acquired(item_id: String)
signal item_used(item_id: String)
signal day_advanced(new_day: int)
signal random_event_triggered(event_id: String)
signal scene_transition_requested(target_scene: String, data: Dictionary)
